export const BASIC_URL = 'http://localhost:3001';
export const CREATE_USER = 'CREATE_USER';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_TIPS = 'GET_TIPS';
export const GET_PROFESSIONALS = "GET_PROFESSIONALS";
export const GET_PROF_BY_USER = "GET_PROF_BY_USER";
export const GET_USERS = "GET_USERS";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_ADMIN_TIPS = "GET_ADMIN_TIPS";
export const PUT_ADMIN_TIPS = "PUT_ADMIN_TIPS";
export const POST_ADMIN_TIPS = "POST_ADMIN_TIPS";
export const DELETE_ADMIN_TIPS = "DELETE_ADMIN_TIPS";
export const GET_ADMIN_REVIEWS = "GET_ADMIN_REVIEWS";
export const PUT_ADMIN_REVIEWS = "PUT_ADMIN_REVIEWS";
export const DELETE_ADMIN_REVIEWS = "DELETE_ADMIN_REVIEWS";
export const GET_ADMIN_USERS = 'GET_ADMIN_USERS';
export const DELETE_ADMIN_USERS = 'DELETE_ADMIN_USERS';
export const PUT_ADMIN_USERS = 'PUT_ADMIN_USERS'
export const DELETE_ADMIN_APPOINTMENT = 'DELETE_ADMIN_APPOINTMENT';
export const PUT_ADMIN_APPOINTMENT = 'PUT_ADMIN_APPOINTMENT';
export const POST_ADMIN_CATEGORY = 'POST_ADMIN_CATEGORY';
export const PUT_ADMIN_CATEGORY = 'PUT_ADMIN_CATEGORY';
export const DELETE_ADMIN_CATEGORY = 'DELETE_ADMIN_CATEGORY';
export const POST_ADMIN_COUNTRY = "POST_ADMIN_COUNTRY";
export const DELETE_ADMIN_COUNTRY = "DELETE_ADMIN_COUNTRY";
export const CLEAN_USER_LOGIN = 'CLEAN_USER_LOGIN';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FILTER_PROF = 'FILTER_PROF';
export const DATA_NOT_FOUND = 'DATA_NOT_FOUND';


export const SET_ERROR = 'SET_ERROR'
export const SET_ADMIN = 'SET_ADMIN'
export const PUT_USER = 'PUT_USER'


export const REMOVE_FROM_CART_ALL = 'REMOVE_FROM_CART_ALL';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const GET_PROF_SCHEDULE= "GET_PROF_SCHEDULE"

export const GOOGLE_ID = '75669810329-vstjoo2cmckb7lhp5nrthdej5bm8cpk6.apps.googleusercontent.com'
